### ISSUE TITLE
rows in orcid search: change default? + max

### ISSUE THREAD

**Issue by jcolomb** [ropensci/rorcid#86]
hello,

I just took 35 min to understand why my search was not returning all elements, until I finally saw that orcid_search() was based on orcid(), that give only 10 rows output...

It would be good if the default could be 50, and if it would give a message when the result is truncated ("only first x results shown").

By the way, why is the max 200? is it due to the api?

background:
I using orcid search to return all researchers that got a special grant (and are therefore part of our consortium), I am then building personal pages from orcid information. 200 should be enough for this case, but would be nice to get over that max.

**Comment by sckott** [comment]
thanks for the issue. I think 10 is a good default. For first time users, we don't want a big default value as we want data returned quickly so users don't get frustrated immediately.  I think pagination through `rows` and `start` parameters is well documented, eg.,  https://docs.ropensci.org/rorcid/reference/orcid_search.html 

I've updated the `orcid_search` function to include the number of results found, can get it programatically by doing `attr(x, "found")` if `x` is the output from `orcid_search`. And added more docs on the results found and pagination.  reinstall to get the change. 

the 200 max is due to ORCID, not this pkg, you can use `start` parameter to offset to get results if there's more than 200
